# Linux nativo: network host + socket X11 do host

services:
  ros-kinect-poc:
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
